export const LOAD_OFFER = `LOAD_OFFER`;
export const LOAD_COMMENTS = `LOAD_COMMENTS`;
export const UPDATE_OFFER = `UPDATE_OFFER`;
export const UPDATE_COMMENTS = `UPDATE_COMMENTS`;
export const SET_REVIEW_FORM_ERROR = `SET_REVIEW_FORM_ERROR`;
export const SET_START_REVIEW_SENDING = `SET_START_REVIEW_SENDING`;
export const SET_FINISH_REVIEW_SENDING = `SET_FINISH_REVIEW_SENDING`;
